"""role_key_competencies

Revision ID: 268a07632d47
Revises: c80a56186ac8
Create Date: 2026-04-24 14:39:00.788805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268a07632d47'
down_revision: Union[str, None] = 'c80a56186ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'role_key_competencies',
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('competency_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('role_id', 'competency_id'),
    )
    # Автодефолт: ключевая компетенция для роли = та, что имеет required_level >= 3
    # на максимальном грейде этой роли (т.е. «без неё не станешь Senior в этой специализации»).
    op.execute("""
        INSERT INTO role_key_competencies (role_id, competency_id)
        SELECT rp.role_id, rp.competency_id
        FROM role_profiles rp
        JOIN grades g ON g.id = rp.grade_id
        JOIN (
            SELECT rp2.role_id, MAX(g2.sort_order) AS max_sort
            FROM role_profiles rp2
            JOIN grades g2 ON g2.id = rp2.grade_id
            WHERE rp2.required_level > 0
            GROUP BY rp2.role_id
        ) mg ON mg.role_id = rp.role_id AND g.sort_order = mg.max_sort
        WHERE rp.required_level >= 3
        ON CONFLICT DO NOTHING
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_key_competencies')
    # ### end Alembic commands ###
