"""drop uniq on competencies.code

Revision ID: 013ae3fc6bc9
Revises: f449415a3b17
Create Date: 2026-04-22 16:50:13.274206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013ae3fc6bc9'
down_revision: Union[str, None] = 'f449415a3b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('competencies_code_key'), 'competencies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('competencies_code_key'), 'competencies', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
