"""meetings.ai_questions_tasks

Revision ID: d8d8e81916ad
Revises: 6529b84e2cb2
Create Date: 2026-04-22 17:19:31.039087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8d8e81916ad'
down_revision: Union[str, None] = '6529b84e2cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('ai_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('meetings', sa.Column('ai_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'ai_tasks')
    op.drop_column('meetings', 'ai_questions')
    # ### end Alembic commands ###
