"""mpk_procedures + meetings.procedure_id

Revision ID: c80a56186ac8
Revises: fffc0a697fb0
Create Date: 2026-04-22 18:22:36.631786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80a56186ac8'
down_revision: Union[str, None] = 'fffc0a697fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Старые встречи удаляем — они вне концепции «процедура оценки».
    # assessment_meetings снимутся каскадом, сами assessments останутся.
    op.execute("DELETE FROM meetings")

    op.create_table('mpk_procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpk_procedures_employee_id'), 'mpk_procedures', ['employee_id'], unique=False)
    op.create_index('ix_mpk_procedures_one_open_per_employee', 'mpk_procedures', ['employee_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.add_column('meetings', sa.Column('procedure_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_meetings_procedure_id'), 'meetings', ['procedure_id'], unique=False)
    op.create_foreign_key(None, 'meetings', 'mpk_procedures', ['procedure_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_index(op.f('ix_meetings_procedure_id'), table_name='meetings')
    op.drop_column('meetings', 'procedure_id')
    op.drop_index('ix_mpk_procedures_one_open_per_employee', table_name='mpk_procedures', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_mpk_procedures_employee_id'), table_name='mpk_procedures')
    op.drop_table('mpk_procedures')
    # ### end Alembic commands ###
