"""assessments.meeting_id

Revision ID: da9e5334ef19
Revises: d8d8e81916ad
Create Date: 2026-04-22 17:35:39.638670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9e5334ef19'
down_revision: Union[str, None] = 'd8d8e81916ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('meeting_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assessments_meeting_id'), 'assessments', ['meeting_id'], unique=False)
    op.create_foreign_key(None, 'assessments', 'meetings', ['meeting_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_index(op.f('ix_assessments_meeting_id'), table_name='assessments')
    op.drop_column('assessments', 'meeting_id')
    # ### end Alembic commands ###
