"""meeting_artifacts

Revision ID: cbe65fdf859a
Revises: 71ff77f2d019
Create Date: 2026-04-24 14:53:46.452510

"""
import json
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe65fdf859a'
down_revision: Union[str, None] = '71ff77f2d019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'meeting_artifacts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('meeting_id', sa.Integer(), nullable=False),
        sa.Column('kind', sa.String(length=30), nullable=False),
        sa.Column('ai_item_uid', sa.String(length=36), nullable=True),
        sa.Column('competency_id', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('meeting_id', 'kind', 'ai_item_uid', name='uq_meeting_artifacts_meeting_kind_itemuid'),
    )
    op.create_index(op.f('ix_meeting_artifacts_ai_item_uid'), 'meeting_artifacts', ['ai_item_uid'], unique=False)
    op.create_index(op.f('ix_meeting_artifacts_meeting_id'), 'meeting_artifacts', ['meeting_id'], unique=False)

    # Backfill uid для существующих AI-items (чтобы артефакты могли к ним привязываться).
    conn = op.get_bind()
    rows = conn.execute(
        sa.text(
            "SELECT id, ai_questions, ai_tasks FROM meetings "
            "WHERE ai_questions IS NOT NULL OR ai_tasks IS NOT NULL"
        )
    ).fetchall()
    for row in rows:
        mid, aq, at = row[0], row[1], row[2]
        if isinstance(aq, str):
            aq = json.loads(aq)
        if isinstance(at, str):
            at = json.loads(at)

        if aq and isinstance(aq.get("items"), list):
            if any("uid" not in it for it in aq["items"]):
                for it in aq["items"]:
                    it.setdefault("uid", uuid4().hex)
                conn.execute(
                    sa.text(
                        "UPDATE meetings SET ai_questions = (:d)::jsonb WHERE id = :id"
                    ),
                    {"d": json.dumps(aq, ensure_ascii=False), "id": mid},
                )

        if at and isinstance(at.get("items"), list):
            if any("uid" not in it for it in at["items"]):
                for it in at["items"]:
                    it.setdefault("uid", uuid4().hex)
                conn.execute(
                    sa.text(
                        "UPDATE meetings SET ai_tasks = (:d)::jsonb WHERE id = :id"
                    ),
                    {"d": json.dumps(at, ensure_ascii=False), "id": mid},
                )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_artifacts_meeting_id'), table_name='meeting_artifacts')
    op.drop_index(op.f('ix_meeting_artifacts_ai_item_uid'), table_name='meeting_artifacts')
    op.drop_table('meeting_artifacts')
    # ### end Alembic commands ###
