"""technology radar phases 2 to 5

Revision ID: 52d9492a8b4a
Revises: e2f6a8c1d4b7
Create Date: 2026-08-07 16:49:35.755806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52d9492a8b4a"
down_revision: Union[str, None] = "e2f6a8c1d4b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "technology_competencies",
        sa.Column("technology_id", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("weight >= 1 AND weight <= 5", name="ck_technology_competencies_weight"),
        sa.ForeignKeyConstraint(["competency_id"], ["competencies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["technology_id"], ["technologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("technology_id", "competency_id"),
    )
    op.create_index(
        op.f("ix_technology_competencies_competency_id"),
        "technology_competencies",
        ["competency_id"],
        unique=False,
    )
    op.create_table(
        "technology_news_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("technology_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("feed_url", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["technology_id"], ["technologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feed_url"),
    )
    op.create_index(
        op.f("ix_technology_news_sources_technology_id"),
        "technology_news_sources",
        ["technology_id"],
        unique=False,
    )
    op.create_table(
        "technology_package_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("technology_id", sa.Integer(), nullable=False),
        sa.Column("ecosystem", sa.String(length=30), nullable=False),
        sa.Column("package_name", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["technology_id"], ["technologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ecosystem", "package_name"),
    )
    op.create_index(
        op.f("ix_technology_package_mappings_technology_id"),
        "technology_package_mappings",
        ["technology_id"],
        unique=False,
    )
    op.create_table(
        "technology_proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("rationale_md", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decision_md", sa.Text(), nullable=True),
        sa.Column("proposed_by", sa.Integer(), nullable=False),
        sa.Column("decided_by", sa.Integer(), nullable=True),
        sa.Column("technology_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('submitted','assessing','approved','rejected','converted')",
            name="ck_technology_proposals_status",
        ),
        sa.ForeignKeyConstraint(["category_id"], ["technology_categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["decided_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["proposed_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["technology_id"], ["technologies.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_technology_proposals_status"), "technology_proposals", ["status"], unique=False
    )
    op.create_table(
        "technology_news_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("technology_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["technology_news_sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["technology_id"], ["technologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        op.f("ix_technology_news_items_technology_id"),
        "technology_news_items",
        ["technology_id"],
        unique=False,
    )
    op.create_table(
        "technology_project_version_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("package_mapping_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["package_mapping_id"], ["technology_package_mappings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("package_mapping_id", "project_id"),
    )
    op.create_index(
        op.f("ix_technology_project_version_evidence_package_mapping_id"),
        "technology_project_version_evidence",
        ["package_mapping_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technology_project_version_evidence_project_id"),
        "technology_project_version_evidence",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "technology_vulnerability_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_evidence_id", sa.Integer(), nullable=False),
        sa.Column("advisory_id", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("is_kev", sa.Boolean(), nullable=False),
        sa.Column("epss", sa.Float(), nullable=True),
        sa.Column("affected", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["version_evidence_id"], ["technology_project_version_evidence.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_evidence_id", "advisory_id"),
    )
    op.create_index(
        op.f("ix_technology_vulnerability_snapshots_version_evidence_id"),
        "technology_vulnerability_snapshots",
        ["version_evidence_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_technology_vulnerability_snapshots_version_evidence_id"),
        table_name="technology_vulnerability_snapshots",
    )
    op.drop_table("technology_vulnerability_snapshots")
    op.drop_index(
        op.f("ix_technology_project_version_evidence_project_id"),
        table_name="technology_project_version_evidence",
    )
    op.drop_index(
        op.f("ix_technology_project_version_evidence_package_mapping_id"),
        table_name="technology_project_version_evidence",
    )
    op.drop_table("technology_project_version_evidence")
    op.drop_index(
        op.f("ix_technology_news_items_technology_id"), table_name="technology_news_items"
    )
    op.drop_table("technology_news_items")
    op.drop_index(op.f("ix_technology_proposals_status"), table_name="technology_proposals")
    op.drop_table("technology_proposals")
    op.drop_index(
        op.f("ix_technology_package_mappings_technology_id"),
        table_name="technology_package_mappings",
    )
    op.drop_table("technology_package_mappings")
    op.drop_index(
        op.f("ix_technology_news_sources_technology_id"), table_name="technology_news_sources"
    )
    op.drop_table("technology_news_sources")
    op.drop_index(
        op.f("ix_technology_competencies_competency_id"), table_name="technology_competencies"
    )
    op.drop_table("technology_competencies")
    # ### end Alembic commands ###
