"""m2m assessment meetings + snapshots

Revision ID: fffc0a697fb0
Revises: da9e5334ef19
Create Date: 2026-04-22 18:06:17.211197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffc0a697fb0'
down_revision: Union[str, None] = 'da9e5334ef19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('assessment_meetings',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id', 'meeting_id')
    )
    # backfill: перенос старых 1:N связей в M:N
    op.execute(
        "INSERT INTO assessment_meetings (assessment_id, meeting_id) "
        "SELECT id, meeting_id FROM assessments WHERE meeting_id IS NOT NULL"
    )
    op.drop_index(op.f('ix_assessments_meeting_id'), table_name='assessments')
    op.drop_constraint(op.f('assessments_meeting_id_fkey'), 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'meeting_id')

    op.add_column('meetings', sa.Column('transcript_md', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('role_snapshot', sa.String(length=255), nullable=True))
    op.add_column('meetings', sa.Column('grade_snapshot', sa.String(length=20), nullable=True))
    # backfill снапшотов из текущего состояния сотрудника
    op.execute(
        "UPDATE meetings m "
        "SET role_snapshot = r.name, grade_snapshot = g.code "
        "FROM employees e "
        "LEFT JOIN roles r ON r.id = e.role_id "
        "LEFT JOIN grades g ON g.id = e.grade_id "
        "WHERE m.employee_id = e.id"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'grade_snapshot')
    op.drop_column('meetings', 'role_snapshot')
    op.drop_column('meetings', 'transcript_md')
    op.add_column('assessments', sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('assessments_meeting_id_fkey'), 'assessments', 'meetings', ['meeting_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_assessments_meeting_id'), 'assessments', ['meeting_id'], unique=False)
    op.drop_table('assessment_meetings')
    # ### end Alembic commands ###
