"""move snapshot meeting to procedure

Revision ID: 71ff77f2d019
Revises: 268a07632d47
Create Date: 2026-04-24 14:46:47.681746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ff77f2d019'
down_revision: Union[str, None] = '268a07632d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'role_snapshot')
    op.drop_column('meetings', 'grade_snapshot')
    op.add_column('mpk_procedures', sa.Column('role_snapshot', sa.String(length=255), nullable=True))
    op.add_column('mpk_procedures', sa.Column('grade_snapshot', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mpk_procedures', 'grade_snapshot')
    op.drop_column('mpk_procedures', 'role_snapshot')
    op.add_column('meetings', sa.Column('grade_snapshot', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('meetings', sa.Column('role_snapshot', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
