import { FormEvent, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'

import {
  EmployeeSearchItem,
  ProductListItem,
  Technology,
  TechnologyLinkKind,
  TechnologyListItem,
  TechnologyMemberRole,
  TechnologyMeta,
  TechnologyStatus,
  TechnologyUsageType,
  api,
} from '../api/client'
import { Markdown } from '../components/Markdown'
import { TechnologyCompetenciesSection, TechnologyIntelligencePanel } from '../components/technology/TechnologyIntelligencePanel'
import { TechnologyIcon, TechnologyIconPicker } from '../components/technology/TechnologyIcon'
import { useAuth } from '../lib/auth-context'
import { TECHNOLOGY_STATUS_VARIANTS, buttonClass, statusClass } from '../lib/ui-variants'

const STATUS_LABEL: Record<TechnologyStatus, string> = { adopt: 'Adopt', trial: 'Trial', assess: 'Assess', hold: 'Hold' }
const ROLE_LABEL: Partial<Record<TechnologyMemberRole, string>> = { leader: 'Лидеры', expert: 'Эксперты' }
const USAGE_LABEL: Record<TechnologyUsageType, string> = { production: 'Production', pilot: 'Пилот', evaluation: 'Оценка', legacy: 'Legacy' }

function fmt(value: string | null) { return value ? new Date(value).toLocaleDateString('ru-RU') : '—' }

function StatusModal({ technology, technologies, onClose, onDone }: {
  technology: Technology; technologies: TechnologyListItem[]; onClose: () => void; onDone: () => void
}) {
  const [status, setStatus] = useState<TechnologyStatus>(technology.status === 'adopt' ? 'trial' : 'adopt')
  const [reason, setReason] = useState('')
  const [nextReview, setNextReview] = useState(technology.next_review_at || '')
  const [replacement, setReplacement] = useState('')
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  const submit = async (e: FormEvent) => { e.preventDefault(); setSaving(true); setError(null); try { await api.technologies.changeStatus(technology.id, { status, reason_md: reason, next_review_at: nextReview || null, replacement_technology_id: replacement ? Number(replacement) : null }); onDone() } catch (err) { setError((err as Error).message) } finally { setSaving(false) } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-bg-elevated p-6 ring-1 ring-white/10"><div className="flex justify-between"><h2 className="text-lg font-semibold">Изменить статус</h2><button type="button" onClick={onClose}>✕</button></div><select value={status} onChange={(e) => setStatus(e.target.value as TechnologyStatus)} className="w-full rounded-lg bg-bg-panel px-3 py-2">{(['adopt', 'trial', 'assess', 'hold'] as TechnologyStatus[]).filter((s) => s !== technology.status).map((s) => <option key={s} value={s}>{STATUS_LABEL[s]}</option>)}</select><textarea required value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Обоснование изменения (обязательно)" className="h-28 w-full rounded-lg bg-bg-panel px-3 py-2 ring-1 ring-white/5" /><label className="block text-xs text-slate-400">Следующий review<input type="date" value={nextReview} onChange={(e) => setNextReview(e.target.value)} className="mt-1 block w-full rounded-lg bg-bg-panel px-3 py-2" /></label><label className="block text-xs text-slate-400">Замена (для Hold рекомендуется)<select value={replacement} onChange={(e) => setReplacement(e.target.value)} className="mt-1 block w-full rounded-lg bg-bg-panel px-3 py-2"><option value="">Не выбрана</option>{technologies.filter((t) => t.id !== technology.id).map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{error && <div className="text-sm text-red-400">{error}</div>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="px-3 py-2 text-sm text-slate-400">Отмена</button><button disabled={saving} className="rounded-lg bg-accent px-4 py-2 text-sm text-bg disabled:opacity-50">{saving ? 'Сохранение…' : 'Сохранить'}</button></div></form></div>
}

function ReviewModal({ technology, onClose, onDone }: {
  technology: Technology
  onClose: () => void
  onDone: () => void
}) {
  const [summary, setSummary] = useState('')
  const [nextReview, setNextReview] = useState(technology.next_review_at || '')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const submit = async (event: FormEvent) => {
    event.preventDefault()
    setSaving(true)
    setError(null)
    try {
      await api.technologies.review(technology.id, {
        summary_md: summary,
        next_review_at: nextReview || null,
      })
      onDone()
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setSaving(false)
    }
  }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-bg-elevated p-6 ring-1 ring-white/10"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">Подтвердить актуальность</h2><p className="mt-1 text-xs text-slate-500">Статус {STATUS_LABEL[technology.status]} останется без изменений.</p></div><button type="button" onClick={onClose}>✕</button></div><textarea autoFocus required value={summary} onChange={(e) => setSummary(e.target.value)} placeholder="Результат review и основание сохранения текущего статуса" className="h-32 w-full rounded-lg bg-bg-panel px-3 py-2 ring-1 ring-white/5 outline-none focus:ring-accent" /><label className="block text-xs text-slate-400">Следующий review<input type="date" value={nextReview} onChange={(e) => setNextReview(e.target.value)} className="mt-1 block w-full rounded-lg bg-bg-panel px-3 py-2 text-sm" /></label>{error && <div className="text-sm text-red-400">{error}</div>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="px-3 py-2 text-sm text-slate-400">Отмена</button><button disabled={saving || !summary.trim()} className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-bg disabled:opacity-50">{saving ? 'Сохранение…' : 'Подтвердить'}</button></div></form></div>
}

export function TechnologyDetail() {
  const id = Number(useParams().id); const navigate = useNavigate(); const { user } = useAuth()
  const [technology, setTechnology] = useState<Technology | null>(null)
  const [meta, setMeta] = useState<TechnologyMeta | null>(null)
  const [all, setAll] = useState<TechnologyListItem[]>([])
  const [products, setProducts] = useState<ProductListItem[]>([])
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const [statusOpen, setStatusOpen] = useState(false); const [editOpen, setEditOpen] = useState(false)
  const [reviewOpen, setReviewOpen] = useState(false)
  const [memberOpen, setMemberOpen] = useState(false); const [productOpen, setProductOpen] = useState(false); const [linkOpen, setLinkOpen] = useState(false)
  const load = async () => { setLoading(true); setError(null); try { const [item, metadata, list, productList] = await Promise.all([api.technologies.get(id), api.technologies.meta(), api.technologies.list(), api.products.list()]); setTechnology(item); setMeta(metadata); setAll(list); setProducts(productList) } catch (err) { setError((err as Error).message) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [id])
  if (loading) return <div className="text-slate-500">Загрузка технологии…</div>
  if (error || !technology) return <div className="text-red-400">{error || 'Технология не найдена'}</div>
  const flags = [technology.attention.overdue_review && 'Просрочен review', technology.attention.no_expertise && 'Нет лидера или эксперта', technology.attention.hold_in_active_products && 'Hold используется активным продуктом'].filter(Boolean)
  const archive = async () => { const reason = prompt('Причина архивации'); if (!reason) return; try { await api.technologies.archive(id, reason); navigate('/technology-radar') } catch (err) { alert((err as Error).message) } }
  const restore = async () => { try { await api.technologies.restore(id); await load() } catch (err) { alert((err as Error).message) } }
  return <div className="space-y-7">
    <button onClick={() => navigate('/technology-radar')} className="text-sm text-slate-400 hover:text-slate-200">← Радар технологий</button>
    <header className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><TechnologyIcon slug={technology.icon_slug} name={technology.name} size={42} /><div><div className="mb-2 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold">{technology.name}</h1><span className={`rounded px-2 py-1 text-xs font-medium ${TECHNOLOGY_STATUS_VARIANTS[technology.status]}`}>{STATUS_LABEL[technology.status]}</span><span className={statusClass('neutral')}>{technology.category.name}</span>{!technology.is_active && <span className={statusClass('neutral')}>В архиве</span>}</div>{technology.replacement && <div className="text-sm text-ink-secondary">Замена: <Link to={`/technology-radar/${technology.replacement.id}`} className="text-primary hover:text-primary-hover">{technology.replacement.name}</Link></div>}<div className="mt-2 text-xs text-ink-muted">Обновлено {fmt(technology.updated_at)} · review {fmt(technology.last_reviewed_at)} → {fmt(technology.next_review_at)}</div></div></div>{user?.is_admin && <div className="flex flex-wrap gap-2">{technology.is_active ? <><button onClick={() => setEditOpen(true)} className={buttonClass('secondary')}>Редактировать</button><button onClick={() => setReviewOpen(true)} className={buttonClass('primary')}>Подтвердить актуальность</button><button onClick={() => setStatusOpen(true)} className={buttonClass('secondary')}>Изменить статус</button><button onClick={archive} className={buttonClass('danger')}>Архивировать</button></> : <button onClick={restore} className={buttonClass('primary')}>Восстановить</button>}</div>}</header>
    {flags.length > 0 && <div className="attention-banner rounded-xl bg-warning-soft p-4 text-sm text-warning ring-1 ring-warning/30" role="alert">⚠ {flags.join(' · ')}</div>}
    <section className="grid grid-cols-2 gap-3 md:grid-cols-5">{[['Продукты', technology.products_count], ['Эксперты', technology.experts_count], ['Лидеры', technology.leaders_count], ['Последний review', fmt(technology.last_reviewed_at)], ['Следующий review', fmt(technology.next_review_at)]].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-bg-elevated p-3 ring-1 ring-white/5"><div className="text-lg font-semibold">{value}</div><div className="text-xs text-slate-500">{label}</div></div>)}</section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-bg-elevated p-5 ring-1 ring-white/5"><h2 className="mb-3 font-semibold">О технологии</h2>{technology.description_md ? <Markdown content={technology.description_md} /> : <div className="text-sm text-slate-500">Описание не заполнено.</div>}</div><div className="rounded-2xl bg-bg-elevated p-5 ring-1 ring-white/5"><h2 className="mb-3 font-semibold">Почему такой статус</h2>{technology.status_reason_md ? <Markdown content={technology.status_reason_md} /> : <div className="text-sm text-slate-500">Основание не заполнено.</div>}</div></section>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Люди</h2>{user?.is_admin && <button onClick={() => setMemberOpen(!memberOpen)} className="text-sm text-accent">+ Добавить</button>}</div>{memberOpen && <MemberForm technologyId={id} existing={new Set(technology.members.map((m) => m.employee_id))} onDone={() => { setMemberOpen(false); void load() }} />}{(['leader', 'expert'] as TechnologyMemberRole[]).map((role) => <div key={role} className="mb-3"><div className="mb-1 text-xs uppercase text-slate-500">{ROLE_LABEL[role]}</div><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{technology.members.filter((m) => m.role === role).map((member) => <div key={member.employee_id} className="rounded-xl bg-bg-elevated p-3 ring-1 ring-white/5"><div className="flex justify-between"><Link to={`/employees/${member.employee_id}`} className="font-medium hover:text-accent">{member.full_name}</Link>{user?.is_admin && <button onClick={async () => { if (confirm('Удалить связь?')) { await api.technologies.members.remove(id, member.employee_id); await load() } }} className="text-xs text-slate-600 hover:text-rose-400">✕</button>}</div><div className="text-xs text-slate-500">{member.role_name || 'Роль не указана'} · {member.grade_code || '—'}{member.department_name ? ` · ${member.department_name}` : ''}</div>{member.notes && <div className="mt-2 text-xs text-slate-400">{member.notes}</div>}{!member.employee_active && <div className="mt-1 text-xs text-rose-400">Неактивен</div>}{user?.is_admin && <div className="mt-2 flex items-center gap-2"><select value={member.role} onChange={async (e) => { await api.technologies.members.update(id, member.employee_id, { role: e.target.value as TechnologyMemberRole }); await load() }} className="rounded bg-bg-panel px-2 py-1 text-xs"><option value="leader">Лидер</option><option value="expert">Эксперт</option></select><button onClick={async () => { const notes = prompt('Комментарий к роли', member.notes || ''); if (notes !== null) { await api.technologies.members.update(id, member.employee_id, { notes: notes || null }); await load() } }} className="text-xs text-slate-500 hover:text-accent">комментарий</button></div>}</div>)}{technology.members.every((m) => m.role !== role) && <div className="text-sm text-slate-600">Нет</div>}</div></div>)}</section>
    <section><div className="mb-3 flex justify-between"><h2 className="font-semibold">Продукты</h2>{user?.is_admin && <button onClick={() => setProductOpen(!productOpen)} className="text-sm text-accent">+ Связать продукт</button>}</div>{productOpen && <ProductForm technologyId={id} products={products.filter((p) => !technology.products.some((x) => x.product_id === p.id))} onDone={() => { setProductOpen(false); void load() }} />}<div className="overflow-hidden rounded-2xl bg-bg-elevated ring-1 ring-white/5">{technology.products.length === 0 ? <div className="p-5 text-sm text-slate-500">Связанных продуктов нет.</div> : technology.products.map((product) => <div key={product.product_id} className={`flex items-center gap-3 border-b border-white/5 px-4 py-3 last:border-0 ${technology.status === 'hold' && product.product_status === 'active' ? 'bg-rose-500/10' : ''}`}><Link to={`/products/${product.product_id}`} className="font-medium hover:text-accent">{product.product_name}</Link>{user?.is_admin ? <select value={product.usage_type} onChange={async (e) => { await api.technologies.products.update(id, product.product_id, { usage_type: e.target.value as TechnologyUsageType }); await load() }} className="rounded bg-bg-panel px-2 py-1 text-xs text-slate-300">{Object.entries(USAGE_LABEL).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select> : <span className="rounded bg-bg-panel px-2 py-1 text-xs text-slate-400">{USAGE_LABEL[product.usage_type]}</span>}<span className="text-xs text-slate-500">{product.notes}</span>{user?.is_admin && <div className="ml-auto flex gap-2"><button onClick={async () => { const notes = prompt('Комментарий к использованию', product.notes || ''); if (notes !== null) { await api.technologies.products.update(id, product.product_id, { notes: notes || null }); await load() } }} className="text-xs text-slate-500 hover:text-accent">комментарий</button><button onClick={async () => { await api.technologies.products.remove(id, product.product_id); await load() }} className="text-xs text-slate-600 hover:text-rose-400">Удалить связь</button></div>}</div>)}</div></section>
    <section><div className="mb-3 flex justify-between"><h2 className="font-semibold">Материалы</h2>{user?.is_admin && <button onClick={() => setLinkOpen(!linkOpen)} className="text-sm text-accent">+ Добавить ссылку</button>}</div>{linkOpen && meta && <LinkForm technologyId={id} meta={meta} onDone={() => { setLinkOpen(false); void load() }} />}<div className="grid gap-2 md:grid-cols-2">{technology.links.map((link) => <div key={link.id} className="flex items-center rounded-xl bg-bg-elevated p-3 ring-1 ring-white/5"><a href={link.url} target="_blank" rel="noreferrer" className="min-w-0 flex-1"><div className="font-medium hover:text-accent">{link.title} ↗</div><div className="truncate text-xs text-slate-500">{link.kind} · {link.url}</div></a>{user?.is_admin && <><button onClick={async () => { const title = prompt('Название материала', link.title); const url = prompt('URL', link.url); if (title && url) { await api.technologies.links.update(id, link.id, { title, url }); await load() } }} className="ml-2 text-xs text-slate-500 hover:text-accent">изменить</button><button onClick={async () => { await api.technologies.links.remove(id, link.id); await load() }} className="ml-2 text-slate-600 hover:text-rose-400">✕</button></>}</div>)}{technology.links.length === 0 && <div className="text-sm text-slate-500">Материалы пока не добавлены.</div>}</div></section>
    <TechnologyCompetenciesSection technologyId={id} isAdmin={Boolean(user?.is_admin)} />
    <TechnologyIntelligencePanel technologyId={id} isAdmin={Boolean(user?.is_admin)} />
    <section><h2 className="mb-3 font-semibold">История решений</h2><div className="space-y-3 border-l border-white/10 pl-5">{technology.decisions.map((decision) => <article key={decision.id} className="relative rounded-xl bg-bg-elevated p-4 ring-1 ring-white/5"><span className="absolute -left-[25px] top-5 h-2 w-2 rounded-full bg-accent" /><div className="mb-2 text-xs text-slate-500">{fmt(decision.created_at)} · {decision.from_status !== decision.to_status ? `${decision.from_status ? STATUS_LABEL[decision.from_status] : 'Создано'} → ${decision.to_status ? STATUS_LABEL[decision.to_status] : '—'}` : decision.event_kind}</div><Markdown content={decision.summary_md} />{decision.next_review_at && <div className="mt-2 text-xs text-slate-500">Следующий review: {fmt(decision.next_review_at)}</div>}</article>)}</div></section>
    {statusOpen && <StatusModal technology={technology} technologies={all} onClose={() => setStatusOpen(false)} onDone={() => { setStatusOpen(false); void load() }} />}
    {reviewOpen && <ReviewModal technology={technology} onClose={() => setReviewOpen(false)} onDone={() => { setReviewOpen(false); void load() }} />}
    {editOpen && meta && <EditModal technology={technology} technologies={all} meta={meta} onClose={() => setEditOpen(false)} onDone={() => { setEditOpen(false); void load() }} />}
  </div>
}

function MemberForm({ technologyId, existing, onDone }: { technologyId: number; existing: Set<number>; onDone: () => void }) {
  const [q, setQ] = useState(''); const [results, setResults] = useState<EmployeeSearchItem[]>([]); const [role, setRole] = useState<TechnologyMemberRole>('expert'); const [error, setError] = useState<string | null>(null)
  const search = async (e: FormEvent) => { e.preventDefault(); try { setResults((await api.employeesSearch(q, 30)).filter((item) => !existing.has(item.id))) } catch (err) { setError((err as Error).message) } }
  return <div className="mb-4 rounded-xl bg-bg-elevated p-3 ring-1 ring-white/5"><form onSubmit={search} className="flex flex-wrap gap-2"><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="ФИО или email" className="min-w-[220px] flex-1 rounded bg-bg-panel px-3 py-2 text-sm" /><select value={role} onChange={(e) => setRole(e.target.value as TechnologyMemberRole)} className="rounded bg-bg-panel px-3 py-2 text-sm"><option value="leader">Лидер</option><option value="expert">Эксперт</option></select><button className="rounded bg-accent/15 px-3 py-2 text-sm text-accent">Найти</button></form>{error && <div className="mt-2 text-xs text-red-400">{error}</div>}<div className="mt-2 space-y-1">{results.map((employee) => <button key={employee.id} onClick={async () => { try { await api.technologies.members.add(technologyId, { employee_id: employee.id, role }); onDone() } catch (err) { setError((err as Error).message) } }} className="block w-full rounded px-2 py-1 text-left text-sm hover:bg-bg-panel">+ {employee.full_name} <span className="text-xs text-slate-500">{employee.role_name} {employee.grade_code}</span></button>)}</div></div>
}

function ProductForm({ technologyId, products, onDone }: { technologyId: number; products: ProductListItem[]; onDone: () => void }) {
  const [productId, setProductId] = useState(products[0]?.id || 0); const [usage, setUsage] = useState<TechnologyUsageType>('production'); const [notes, setNotes] = useState(''); const [error, setError] = useState<string | null>(null)
  const submit = async (e: FormEvent) => { e.preventDefault(); try { await api.technologies.products.add(technologyId, { product_id: productId, usage_type: usage, notes: notes || null }); onDone() } catch (err) { setError((err as Error).message) } }
  return <form onSubmit={submit} className="mb-3 flex flex-wrap gap-2 rounded-xl bg-bg-elevated p-3 ring-1 ring-white/5"><select value={productId} onChange={(e) => setProductId(Number(e.target.value))} className="min-w-[220px] flex-1 rounded bg-bg-panel px-3 py-2 text-sm">{products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={usage} onChange={(e) => setUsage(e.target.value as TechnologyUsageType)} className="rounded bg-bg-panel px-3 py-2 text-sm">{Object.entries(USAGE_LABEL).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Комментарий" className="rounded bg-bg-panel px-3 py-2 text-sm" /><button disabled={!productId} className="rounded bg-accent/15 px-3 py-2 text-sm text-accent">Добавить</button>{error && <div className="w-full text-xs text-red-400">{error}</div>}</form>
}

function LinkForm({ technologyId, meta, onDone }: { technologyId: number; meta: TechnologyMeta; onDone: () => void }) {
  const [kind, setKind] = useState<TechnologyLinkKind>('documentation'); const [title, setTitle] = useState(''); const [url, setUrl] = useState(''); const [error, setError] = useState<string | null>(null)
  const submit = async (e: FormEvent) => { e.preventDefault(); try { await api.technologies.links.add(technologyId, { kind, title, url }); onDone() } catch (err) { setError((err as Error).message) } }
  return <form onSubmit={submit} className="mb-3 flex flex-wrap gap-2 rounded-xl bg-bg-elevated p-3 ring-1 ring-white/5"><select value={kind} onChange={(e) => setKind(e.target.value as TechnologyLinkKind)} className="rounded bg-bg-panel px-3 py-2 text-sm">{meta.link_kinds.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Название" className="flex-1 rounded bg-bg-panel px-3 py-2 text-sm" /><input required value={url} onChange={(e) => setUrl(e.target.value)} placeholder="URL" className="min-w-[260px] flex-1 rounded bg-bg-panel px-3 py-2 text-sm" /><button className="rounded bg-accent/15 px-3 py-2 text-sm text-accent">Добавить</button>{error && <div className="w-full text-xs text-red-400">{error}</div>}</form>
}

function EditModal({ technology, technologies, meta, onClose, onDone }: { technology: Technology; technologies: TechnologyListItem[]; meta: TechnologyMeta; onClose: () => void; onDone: () => void }) {
  const [name, setName] = useState(technology.name); const [iconSlug, setIconSlug] = useState<string | null>(technology.icon_slug); const [categoryId, setCategoryId] = useState(technology.category.id); const [description, setDescription] = useState(technology.description_md || ''); const [nextReview, setNextReview] = useState(technology.next_review_at || ''); const [replacement, setReplacement] = useState(technology.replacement?.id ? String(technology.replacement.id) : ''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  const submit = async (e: FormEvent) => { e.preventDefault(); setSaving(true); try { await api.technologies.update(technology.id, { name, icon_slug: iconSlug, category_id: categoryId, description_md: description || null, next_review_at: nextReview || null, replacement_technology_id: replacement ? Number(replacement) : null }); onDone() } catch (err) { setError((err as Error).message) } finally { setSaving(false) } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-bg-elevated p-6 ring-1 ring-white/10"><div className="flex justify-between"><h2 className="text-lg font-semibold">Редактировать технологию</h2><button type="button" onClick={onClose}>✕</button></div><input required value={name} onChange={(e) => setName(e.target.value)} className="w-full rounded bg-bg-panel px-3 py-2" /><TechnologyIconPicker name={name} value={iconSlug} onChange={setIconSlug} /><select value={categoryId} onChange={(e) => setCategoryId(Number(e.target.value))} className="w-full rounded bg-bg-panel px-3 py-2">{meta.categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea value={description} onChange={(e) => setDescription(e.target.value)} className="h-32 w-full rounded bg-bg-panel px-3 py-2" /><label className="block text-xs text-slate-400">Технология-замена<select value={replacement} onChange={(e) => setReplacement(e.target.value)} className="mt-1 block w-full rounded bg-bg-panel px-3 py-2 text-sm"><option value="">Не выбрана</option>{technologies.filter((item) => item.id !== technology.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-xs text-slate-400">Следующий review<input type="date" value={nextReview} onChange={(e) => setNextReview(e.target.value)} className="mt-1 block w-full rounded bg-bg-panel px-3 py-2 text-sm" /></label>{error && <div className="text-sm text-red-400">{error}</div>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="px-3 py-2 text-slate-400">Отмена</button><button disabled={saving} className="rounded bg-accent px-4 py-2 text-bg">{saving ? 'Сохранение…' : 'Сохранить'}</button></div></form></div>
}
