// Generated by scripts/generate-technology-icons.mjs. Do not edit manually.
import icon0 from 'simple-icons/icons/actix.svg?no-inline'
import icon1 from 'simple-icons/icons/angular.svg?no-inline'
import icon2 from 'simple-icons/icons/ansible.svg?no-inline'
import icon3 from 'simple-icons/icons/antdesign.svg?no-inline'
import icon4 from 'simple-icons/icons/apacheairflow.svg?no-inline'
import icon5 from 'simple-icons/icons/apacheavro.svg?no-inline'
import icon6 from 'simple-icons/icons/apachecassandra.svg?no-inline'
import icon7 from 'simple-icons/icons/apacheflink.svg?no-inline'
import icon8 from 'simple-icons/icons/apachejmeter.svg?no-inline'
import icon9 from 'simple-icons/icons/apachekafka.svg?no-inline'
import icon10 from 'simple-icons/icons/apachemaven.svg?no-inline'
import icon11 from 'simple-icons/icons/apachepulsar.svg?no-inline'
import icon12 from 'simple-icons/icons/apachesolr.svg?no-inline'
import icon13 from 'simple-icons/icons/apachespark.svg?no-inline'
import icon14 from 'simple-icons/icons/astro.svg?no-inline'
import icon15 from 'simple-icons/icons/bootstrap.svg?no-inline'
import icon16 from 'simple-icons/icons/bun.svg?no-inline'
import icon17 from 'simple-icons/icons/cplusplus.svg?no-inline'
import icon18 from 'simple-icons/icons/celery.svg?no-inline'
import icon19 from 'simple-icons/icons/chakraui.svg?no-inline'
import icon20 from 'simple-icons/icons/clickhouse.svg?no-inline'
import icon21 from 'simple-icons/icons/clojure.svg?no-inline'
import icon22 from 'simple-icons/icons/cmake.svg?no-inline'
import icon23 from 'simple-icons/icons/composer.svg?no-inline'
import icon24 from 'simple-icons/icons/couchbase.svg?no-inline'
import icon25 from 'simple-icons/icons/cypress.svg?no-inline'
import icon26 from 'simple-icons/icons/dart.svg?no-inline'
import icon27 from 'simple-icons/icons/datadog.svg?no-inline'
import icon28 from 'simple-icons/icons/delphi.svg?no-inline'
import icon29 from 'simple-icons/icons/dependabot.svg?no-inline'
import icon30 from 'simple-icons/icons/django.svg?no-inline'
import icon31 from 'simple-icons/icons/docker.svg?no-inline'
import icon32 from 'simple-icons/icons/docusaurus.svg?no-inline'
import icon33 from 'simple-icons/icons/elasticsearch.svg?no-inline'
import icon34 from 'simple-icons/icons/elixir.svg?no-inline'
import icon35 from 'simple-icons/icons/envoyproxy.svg?no-inline'
import icon36 from 'simple-icons/icons/erlang.svg?no-inline'
import icon37 from 'simple-icons/icons/esbuild.svg?no-inline'
import icon38 from 'simple-icons/icons/express.svg?no-inline'
import icon39 from 'simple-icons/icons/fsharp.svg?no-inline'
import icon40 from 'simple-icons/icons/fastapi.svg?no-inline'
import icon41 from 'simple-icons/icons/fastify.svg?no-inline'
import icon42 from 'simple-icons/icons/flask.svg?no-inline'
import icon43 from 'simple-icons/icons/fluentbit.svg?no-inline'
import icon44 from 'simple-icons/icons/fluentd.svg?no-inline'
import icon45 from 'simple-icons/icons/flux.svg?no-inline'
import icon46 from 'simple-icons/icons/gatling.svg?no-inline'
import icon47 from 'simple-icons/icons/gin.svg?no-inline'
import icon48 from 'simple-icons/icons/git.svg?no-inline'
import icon49 from 'simple-icons/icons/githubactions.svg?no-inline'
import icon50 from 'simple-icons/icons/go.svg?no-inline'
import icon51 from 'simple-icons/icons/googlebigquery.svg?no-inline'
import icon52 from 'simple-icons/icons/gradle.svg?no-inline'
import icon53 from 'simple-icons/icons/grafana.svg?no-inline'
import icon54 from 'simple-icons/icons/graphql.svg?no-inline'
import icon55 from 'simple-icons/icons/gunicorn.svg?no-inline'
import icon56 from 'simple-icons/icons/haskell.svg?no-inline'
import icon57 from 'simple-icons/icons/helm.svg?no-inline'
import icon58 from 'simple-icons/icons/hibernate.svg?no-inline'
import icon59 from 'simple-icons/icons/htmx.svg?no-inline'
import icon60 from 'simple-icons/icons/huggingface.svg?no-inline'
import icon61 from 'simple-icons/icons/jaeger.svg?no-inline'
import icon62 from 'simple-icons/icons/javascript.svg?no-inline'
import icon63 from 'simple-icons/icons/jenkins.svg?no-inline'
import icon64 from 'simple-icons/icons/jest.svg?no-inline'
import icon65 from 'simple-icons/icons/jquery.svg?no-inline'
import icon66 from 'simple-icons/icons/julia.svg?no-inline'
import icon67 from 'simple-icons/icons/junit5.svg?no-inline'
import icon68 from 'simple-icons/icons/k6.svg?no-inline'
import icon69 from 'simple-icons/icons/keras.svg?no-inline'
import icon70 from 'simple-icons/icons/keycloak.svg?no-inline'
import icon71 from 'simple-icons/icons/kibana.svg?no-inline'
import icon72 from 'simple-icons/icons/koa.svg?no-inline'
import icon73 from 'simple-icons/icons/kong.svg?no-inline'
import icon74 from 'simple-icons/icons/kotlin.svg?no-inline'
import icon75 from 'simple-icons/icons/kubernetes.svg?no-inline'
import icon76 from 'simple-icons/icons/langchain.svg?no-inline'
import icon77 from 'simple-icons/icons/laravel.svg?no-inline'
import icon78 from 'simple-icons/icons/lit.svg?no-inline'
import icon79 from 'simple-icons/icons/logstash.svg?no-inline'
import icon80 from 'simple-icons/icons/lua.svg?no-inline'
import icon81 from 'simple-icons/icons/make.svg?no-inline'
import icon82 from 'simple-icons/icons/mariadb.svg?no-inline'
import icon83 from 'simple-icons/icons/markdown.svg?no-inline'
import icon84 from 'simple-icons/icons/mermaid.svg?no-inline'
import icon85 from 'simple-icons/icons/minio.svg?no-inline'
import icon86 from 'simple-icons/icons/mlflow.svg?no-inline'
import icon87 from 'simple-icons/icons/mobx.svg?no-inline'
import icon88 from 'simple-icons/icons/mocha.svg?no-inline'
import icon89 from 'simple-icons/icons/mongodb.svg?no-inline'
import icon90 from 'simple-icons/icons/mui.svg?no-inline'
import icon91 from 'simple-icons/icons/mysql.svg?no-inline'
import icon92 from 'simple-icons/icons/natsdotio.svg?no-inline'
import icon93 from 'simple-icons/icons/neo4j.svg?no-inline'
import icon94 from 'simple-icons/icons/nestjs.svg?no-inline'
import icon95 from 'simple-icons/icons/nextdotjs.svg?no-inline'
import icon96 from 'simple-icons/icons/nginx.svg?no-inline'
import icon97 from 'simple-icons/icons/npm.svg?no-inline'
import icon98 from 'simple-icons/icons/nuget.svg?no-inline'
import icon99 from 'simple-icons/icons/numpy.svg?no-inline'
import icon100 from 'simple-icons/icons/nuxt.svg?no-inline'
import icon101 from 'simple-icons/icons/onnx.svg?no-inline'
import icon102 from 'simple-icons/icons/opensearch.svg?no-inline'
import icon103 from 'simple-icons/icons/opentelemetry.svg?no-inline'
import icon104 from 'simple-icons/icons/opentofu.svg?no-inline'
import icon105 from 'simple-icons/icons/packer.svg?no-inline'
import icon106 from 'simple-icons/icons/pandas.svg?no-inline'
import icon107 from 'simple-icons/icons/phoenixframework.svg?no-inline'
import icon108 from 'simple-icons/icons/php.svg?no-inline'
import icon109 from 'simple-icons/icons/pinia.svg?no-inline'
import icon110 from 'simple-icons/icons/pnpm.svg?no-inline'
import icon111 from 'simple-icons/icons/podman.svg?no-inline'
import icon112 from 'simple-icons/icons/poetry.svg?no-inline'
import icon113 from 'simple-icons/icons/polars.svg?no-inline'
import icon114 from 'simple-icons/icons/postgresql.svg?no-inline'
import icon115 from 'simple-icons/icons/prefect.svg?no-inline'
import icon116 from 'simple-icons/icons/prometheus.svg?no-inline'
import icon117 from 'simple-icons/icons/pulumi.svg?no-inline'
import icon118 from 'simple-icons/icons/pydantic.svg?no-inline'
import icon119 from 'simple-icons/icons/pytest.svg?no-inline'
import icon120 from 'simple-icons/icons/python.svg?no-inline'
import icon121 from 'simple-icons/icons/pytorch.svg?no-inline'
import icon122 from 'simple-icons/icons/quarkus.svg?no-inline'
import icon123 from 'simple-icons/icons/qwik.svg?no-inline'
import icon124 from 'simple-icons/icons/r.svg?no-inline'
import icon125 from 'simple-icons/icons/rabbitmq.svg?no-inline'
import icon126 from 'simple-icons/icons/react.svg?no-inline'
import icon127 from 'simple-icons/icons/reactquery.svg?no-inline'
import icon128 from 'simple-icons/icons/reactivex.svg?no-inline'
import icon129 from 'simple-icons/icons/redhatopenshift.svg?no-inline'
import icon130 from 'simple-icons/icons/redis.svg?no-inline'
import icon131 from 'simple-icons/icons/redux.svg?no-inline'
import icon132 from 'simple-icons/icons/remix.svg?no-inline'
import icon133 from 'simple-icons/icons/renovate.svg?no-inline'
import icon134 from 'simple-icons/icons/rollupdotjs.svg?no-inline'
import icon135 from 'simple-icons/icons/ruby.svg?no-inline'
import icon136 from 'simple-icons/icons/rubyonrails.svg?no-inline'
import icon137 from 'simple-icons/icons/rust.svg?no-inline'
import icon138 from 'simple-icons/icons/scala.svg?no-inline'
import icon139 from 'simple-icons/icons/scikitlearn.svg?no-inline'
import icon140 from 'simple-icons/icons/scipy.svg?no-inline'
import icon141 from 'simple-icons/icons/scylladb.svg?no-inline'
import icon142 from 'simple-icons/icons/selenium.svg?no-inline'
import icon143 from 'simple-icons/icons/sentry.svg?no-inline'
import icon144 from 'simple-icons/icons/shadcnui.svg?no-inline'
import icon145 from 'simple-icons/icons/sharp.svg?no-inline'
import icon146 from 'simple-icons/icons/shell.svg?no-inline'
import icon147 from 'simple-icons/icons/snowflake.svg?no-inline'
import icon148 from 'simple-icons/icons/snyk.svg?no-inline'
import icon149 from 'simple-icons/icons/solid.svg?no-inline'
import icon150 from 'simple-icons/icons/sonar.svg?no-inline'
import icon151 from 'simple-icons/icons/sphinx.svg?no-inline'
import icon152 from 'simple-icons/icons/spring_creators.svg?no-inline'
import icon153 from 'simple-icons/icons/springboot.svg?no-inline'
import icon154 from 'simple-icons/icons/sqlalchemy.svg?no-inline'
import icon155 from 'simple-icons/icons/sqlite.svg?no-inline'
import icon156 from 'simple-icons/icons/storybook.svg?no-inline'
import icon157 from 'simple-icons/icons/svelte.svg?no-inline'
import icon158 from 'simple-icons/icons/swagger.svg?no-inline'
import icon159 from 'simple-icons/icons/swift.svg?no-inline'
import icon160 from 'simple-icons/icons/symfony.svg?no-inline'
import icon161 from 'simple-icons/icons/tailwindcss.svg?no-inline'
import icon162 from 'simple-icons/icons/teamcity.svg?no-inline'
import icon163 from 'simple-icons/icons/tensorflow.svg?no-inline'
import icon164 from 'simple-icons/icons/terraform.svg?no-inline'
import icon165 from 'simple-icons/icons/trivy.svg?no-inline'
import icon166 from 'simple-icons/icons/typescript.svg?no-inline'
import icon167 from 'simple-icons/icons/uv.svg?no-inline'
import icon168 from 'simple-icons/icons/vagrant.svg?no-inline'
import icon169 from 'simple-icons/icons/vault.svg?no-inline'
import icon170 from 'simple-icons/icons/vite.svg?no-inline'
import icon171 from 'simple-icons/icons/vitest.svg?no-inline'
import icon172 from 'simple-icons/icons/vuedotjs.svg?no-inline'
import icon173 from 'simple-icons/icons/webpack.svg?no-inline'
import icon174 from 'simple-icons/icons/yarn.svg?no-inline'

export interface TechnologyIconDefinition { slug: string; title: string; hex: string; url: string }

export const TECHNOLOGY_ICON_OPTIONS: TechnologyIconDefinition[] = [
  { slug: "actix", title: "Actix", hex: "#000000", url: icon0 },
  { slug: "angular", title: "Angular", hex: "#0F0F11", url: icon1 },
  { slug: "ansible", title: "Ansible", hex: "#EE0000", url: icon2 },
  { slug: "antdesign", title: "Ant Design", hex: "#0170FE", url: icon3 },
  { slug: "apacheairflow", title: "Apache Airflow", hex: "#017CEE", url: icon4 },
  { slug: "apacheavro", title: "Apache Avro", hex: "#30638E", url: icon5 },
  { slug: "apachecassandra", title: "Apache Cassandra", hex: "#1287B1", url: icon6 },
  { slug: "apacheflink", title: "Apache Flink", hex: "#E6526F", url: icon7 },
  { slug: "apachejmeter", title: "Apache JMeter", hex: "#D22128", url: icon8 },
  { slug: "apachekafka", title: "Apache Kafka", hex: "#231F20", url: icon9 },
  { slug: "apachemaven", title: "Apache Maven", hex: "#C71A36", url: icon10 },
  { slug: "apachepulsar", title: "Apache Pulsar", hex: "#188FFF", url: icon11 },
  { slug: "apachesolr", title: "Apache Solr", hex: "#D9411E", url: icon12 },
  { slug: "apachespark", title: "Apache Spark", hex: "#E25A1C", url: icon13 },
  { slug: "astro", title: "Astro", hex: "#BC52EE", url: icon14 },
  { slug: "bootstrap", title: "Bootstrap", hex: "#7952B3", url: icon15 },
  { slug: "bun", title: "Bun", hex: "#000000", url: icon16 },
  { slug: "cplusplus", title: "C++", hex: "#00599C", url: icon17 },
  { slug: "celery", title: "Celery", hex: "#37814A", url: icon18 },
  { slug: "chakraui", title: "Chakra UI", hex: "#1BB2A9", url: icon19 },
  { slug: "clickhouse", title: "ClickHouse", hex: "#FFCC01", url: icon20 },
  { slug: "clojure", title: "Clojure", hex: "#5881D8", url: icon21 },
  { slug: "cmake", title: "CMake", hex: "#064F8C", url: icon22 },
  { slug: "composer", title: "Composer", hex: "#885630", url: icon23 },
  { slug: "couchbase", title: "Couchbase", hex: "#EA2328", url: icon24 },
  { slug: "cypress", title: "Cypress", hex: "#69D3A7", url: icon25 },
  { slug: "dart", title: "Dart", hex: "#0175C2", url: icon26 },
  { slug: "datadog", title: "Datadog", hex: "#632CA6", url: icon27 },
  { slug: "delphi", title: "Delphi", hex: "#E62431", url: icon28 },
  { slug: "dependabot", title: "Dependabot", hex: "#025E8C", url: icon29 },
  { slug: "django", title: "Django", hex: "#092E20", url: icon30 },
  { slug: "docker", title: "Docker", hex: "#2496ED", url: icon31 },
  { slug: "docusaurus", title: "Docusaurus", hex: "#3ECC5F", url: icon32 },
  { slug: "elasticsearch", title: "Elasticsearch", hex: "#005571", url: icon33 },
  { slug: "elixir", title: "Elixir", hex: "#4B275F", url: icon34 },
  { slug: "envoyproxy", title: "Envoy Proxy", hex: "#AC6199", url: icon35 },
  { slug: "erlang", title: "Erlang", hex: "#A90533", url: icon36 },
  { slug: "esbuild", title: "esbuild", hex: "#FFCF00", url: icon37 },
  { slug: "express", title: "Express", hex: "#0A0A0A", url: icon38 },
  { slug: "fsharp", title: "F#", hex: "#378BBA", url: icon39 },
  { slug: "fastapi", title: "FastAPI", hex: "#009688", url: icon40 },
  { slug: "fastify", title: "Fastify", hex: "#000000", url: icon41 },
  { slug: "flask", title: "Flask", hex: "#3BABC3", url: icon42 },
  { slug: "fluentbit", title: "Fluent Bit", hex: "#49BDA5", url: icon43 },
  { slug: "fluentd", title: "Fluentd", hex: "#0E83C8", url: icon44 },
  { slug: "flux", title: "Flux", hex: "#5468FF", url: icon45 },
  { slug: "gatling", title: "Gatling", hex: "#FF9E2A", url: icon46 },
  { slug: "gin", title: "Gin", hex: "#008ECF", url: icon47 },
  { slug: "git", title: "Git", hex: "#F03C2E", url: icon48 },
  { slug: "githubactions", title: "GitHub Actions", hex: "#2088FF", url: icon49 },
  { slug: "go", title: "Go", hex: "#00ADD8", url: icon50 },
  { slug: "googlebigquery", title: "Google BigQuery", hex: "#669DF6", url: icon51 },
  { slug: "gradle", title: "Gradle", hex: "#02303A", url: icon52 },
  { slug: "grafana", title: "Grafana", hex: "#F46800", url: icon53 },
  { slug: "graphql", title: "GraphQL", hex: "#E10098", url: icon54 },
  { slug: "gunicorn", title: "Gunicorn", hex: "#499848", url: icon55 },
  { slug: "haskell", title: "Haskell", hex: "#5D4F85", url: icon56 },
  { slug: "helm", title: "Helm", hex: "#0F1689", url: icon57 },
  { slug: "hibernate", title: "Hibernate", hex: "#59666C", url: icon58 },
  { slug: "htmx", title: "htmx", hex: "#3366CC", url: icon59 },
  { slug: "huggingface", title: "Hugging Face", hex: "#FFD21E", url: icon60 },
  { slug: "jaeger", title: "Jaeger", hex: "#66CFE3", url: icon61 },
  { slug: "javascript", title: "JavaScript", hex: "#F7DF1E", url: icon62 },
  { slug: "jenkins", title: "Jenkins", hex: "#D24939", url: icon63 },
  { slug: "jest", title: "Jest", hex: "#C21325", url: icon64 },
  { slug: "jquery", title: "jQuery", hex: "#0769AD", url: icon65 },
  { slug: "julia", title: "Julia", hex: "#9558B2", url: icon66 },
  { slug: "junit5", title: "JUnit5", hex: "#25A162", url: icon67 },
  { slug: "k6", title: "k6", hex: "#7D64FF", url: icon68 },
  { slug: "keras", title: "Keras", hex: "#D00000", url: icon69 },
  { slug: "keycloak", title: "Keycloak", hex: "#4D4D4D", url: icon70 },
  { slug: "kibana", title: "Kibana", hex: "#005571", url: icon71 },
  { slug: "koa", title: "Koa", hex: "#33333D", url: icon72 },
  { slug: "kong", title: "Kong", hex: "#003459", url: icon73 },
  { slug: "kotlin", title: "Kotlin", hex: "#7F52FF", url: icon74 },
  { slug: "kubernetes", title: "Kubernetes", hex: "#326CE5", url: icon75 },
  { slug: "langchain", title: "LangChain", hex: "#7FC8FF", url: icon76 },
  { slug: "laravel", title: "Laravel", hex: "#FF2D20", url: icon77 },
  { slug: "lit", title: "Lit", hex: "#324FFF", url: icon78 },
  { slug: "logstash", title: "Logstash", hex: "#005571", url: icon79 },
  { slug: "lua", title: "Lua", hex: "#000080", url: icon80 },
  { slug: "make", title: "Make", hex: "#6D00CC", url: icon81 },
  { slug: "mariadb", title: "MariaDB", hex: "#003545", url: icon82 },
  { slug: "markdown", title: "Markdown", hex: "#000000", url: icon83 },
  { slug: "mermaid", title: "Mermaid", hex: "#FF3670", url: icon84 },
  { slug: "minio", title: "MinIO", hex: "#C72E49", url: icon85 },
  { slug: "mlflow", title: "MLflow", hex: "#0194E2", url: icon86 },
  { slug: "mobx", title: "MobX", hex: "#FF9955", url: icon87 },
  { slug: "mocha", title: "Mocha", hex: "#8D6748", url: icon88 },
  { slug: "mongodb", title: "MongoDB", hex: "#47A248", url: icon89 },
  { slug: "mui", title: "MUI", hex: "#007FFF", url: icon90 },
  { slug: "mysql", title: "MySQL", hex: "#4479A1", url: icon91 },
  { slug: "natsdotio", title: "NATS.io", hex: "#27AAE1", url: icon92 },
  { slug: "neo4j", title: "Neo4j", hex: "#4581C3", url: icon93 },
  { slug: "nestjs", title: "NestJS", hex: "#E0234E", url: icon94 },
  { slug: "nextdotjs", title: "Next.js", hex: "#000000", url: icon95 },
  { slug: "nginx", title: "NGINX", hex: "#009639", url: icon96 },
  { slug: "npm", title: "npm", hex: "#CB3837", url: icon97 },
  { slug: "nuget", title: "NuGet", hex: "#004880", url: icon98 },
  { slug: "numpy", title: "NumPy", hex: "#013243", url: icon99 },
  { slug: "nuxt", title: "Nuxt", hex: "#00DC82", url: icon100 },
  { slug: "onnx", title: "ONNX", hex: "#005CED", url: icon101 },
  { slug: "opensearch", title: "OpenSearch", hex: "#005EB8", url: icon102 },
  { slug: "opentelemetry", title: "OpenTelemetry", hex: "#000000", url: icon103 },
  { slug: "opentofu", title: "OpenTofu", hex: "#FFDA18", url: icon104 },
  { slug: "packer", title: "Packer", hex: "#02A8EF", url: icon105 },
  { slug: "pandas", title: "pandas", hex: "#150458", url: icon106 },
  { slug: "phoenixframework", title: "Phoenix Framework", hex: "#FD4F00", url: icon107 },
  { slug: "php", title: "PHP", hex: "#777BB4", url: icon108 },
  { slug: "pinia", title: "Pinia", hex: "#FFD859", url: icon109 },
  { slug: "pnpm", title: "pnpm", hex: "#F69220", url: icon110 },
  { slug: "podman", title: "Podman", hex: "#892CA0", url: icon111 },
  { slug: "poetry", title: "Poetry", hex: "#60A5FA", url: icon112 },
  { slug: "polars", title: "Polars", hex: "#0075FF", url: icon113 },
  { slug: "postgresql", title: "PostgreSQL", hex: "#4169E1", url: icon114 },
  { slug: "prefect", title: "Prefect", hex: "#070E10", url: icon115 },
  { slug: "prometheus", title: "Prometheus", hex: "#E6522C", url: icon116 },
  { slug: "pulumi", title: "Pulumi", hex: "#8A3391", url: icon117 },
  { slug: "pydantic", title: "Pydantic", hex: "#E92063", url: icon118 },
  { slug: "pytest", title: "Pytest", hex: "#0A9EDC", url: icon119 },
  { slug: "python", title: "Python", hex: "#3776AB", url: icon120 },
  { slug: "pytorch", title: "PyTorch", hex: "#EE4C2C", url: icon121 },
  { slug: "quarkus", title: "Quarkus", hex: "#4695EB", url: icon122 },
  { slug: "qwik", title: "Qwik", hex: "#AC7EF4", url: icon123 },
  { slug: "r", title: "R", hex: "#276DC3", url: icon124 },
  { slug: "rabbitmq", title: "RabbitMQ", hex: "#FF6600", url: icon125 },
  { slug: "react", title: "React", hex: "#61DAFB", url: icon126 },
  { slug: "reactquery", title: "React Query", hex: "#FF4154", url: icon127 },
  { slug: "reactivex", title: "ReactiveX", hex: "#B7178C", url: icon128 },
  { slug: "redhatopenshift", title: "Red Hat Open Shift", hex: "#EE0000", url: icon129 },
  { slug: "redis", title: "Redis", hex: "#FF4438", url: icon130 },
  { slug: "redux", title: "Redux", hex: "#764ABC", url: icon131 },
  { slug: "remix", title: "Remix", hex: "#000000", url: icon132 },
  { slug: "renovate", title: "Renovate", hex: "#308BE3", url: icon133 },
  { slug: "rollupdotjs", title: "rollup.js", hex: "#EC4A3F", url: icon134 },
  { slug: "ruby", title: "Ruby", hex: "#CC342D", url: icon135 },
  { slug: "rubyonrails", title: "Ruby on Rails", hex: "#D30001", url: icon136 },
  { slug: "rust", title: "Rust", hex: "#000000", url: icon137 },
  { slug: "scala", title: "Scala", hex: "#DC322F", url: icon138 },
  { slug: "scikitlearn", title: "scikit-learn", hex: "#F7931E", url: icon139 },
  { slug: "scipy", title: "SciPy", hex: "#8CAAE6", url: icon140 },
  { slug: "scylladb", title: "ScyllaDB", hex: "#6CD5E7", url: icon141 },
  { slug: "selenium", title: "Selenium", hex: "#43B02A", url: icon142 },
  { slug: "sentry", title: "Sentry", hex: "#362D59", url: icon143 },
  { slug: "shadcnui", title: "shadcn/ui", hex: "#000000", url: icon144 },
  { slug: "sharp", title: "sharp", hex: "#99CC00", url: icon145 },
  { slug: "shell", title: "Shell", hex: "#FFD500", url: icon146 },
  { slug: "snowflake", title: "Snowflake", hex: "#29B5E8", url: icon147 },
  { slug: "snyk", title: "Snyk", hex: "#4C4A73", url: icon148 },
  { slug: "solid", title: "Solid", hex: "#2C4F7C", url: icon149 },
  { slug: "sonar", title: "Sonar", hex: "#FD3456", url: icon150 },
  { slug: "sphinx", title: "Sphinx", hex: "#000000", url: icon151 },
  { slug: "spring_creators", title: "Spring", hex: "#000000", url: icon152 },
  { slug: "springboot", title: "Spring Boot", hex: "#6DB33F", url: icon153 },
  { slug: "sqlalchemy", title: "SQLAlchemy", hex: "#D71F00", url: icon154 },
  { slug: "sqlite", title: "SQLite", hex: "#003B57", url: icon155 },
  { slug: "storybook", title: "Storybook", hex: "#FF4785", url: icon156 },
  { slug: "svelte", title: "Svelte", hex: "#FF3E00", url: icon157 },
  { slug: "swagger", title: "Swagger", hex: "#85EA2D", url: icon158 },
  { slug: "swift", title: "Swift", hex: "#F05138", url: icon159 },
  { slug: "symfony", title: "Symfony", hex: "#000000", url: icon160 },
  { slug: "tailwindcss", title: "Tailwind CSS", hex: "#06B6D4", url: icon161 },
  { slug: "teamcity", title: "TeamCity", hex: "#000000", url: icon162 },
  { slug: "tensorflow", title: "TensorFlow", hex: "#FF6F00", url: icon163 },
  { slug: "terraform", title: "Terraform", hex: "#844FBA", url: icon164 },
  { slug: "trivy", title: "Trivy", hex: "#1904DA", url: icon165 },
  { slug: "typescript", title: "TypeScript", hex: "#3178C6", url: icon166 },
  { slug: "uv", title: "uv", hex: "#DE5FE9", url: icon167 },
  { slug: "vagrant", title: "Vagrant", hex: "#1868F2", url: icon168 },
  { slug: "vault", title: "Vault", hex: "#FFEC6E", url: icon169 },
  { slug: "vite", title: "Vite", hex: "#9135FF", url: icon170 },
  { slug: "vitest", title: "Vitest", hex: "#00FF74", url: icon171 },
  { slug: "vuedotjs", title: "Vue.js", hex: "#4FC08D", url: icon172 },
  { slug: "webpack", title: "Webpack", hex: "#8DD6F9", url: icon173 },
  { slug: "yarn", title: "Yarn", hex: "#2C8EBB", url: icon174 },
]

export const TECHNOLOGY_ICONS = new Map(TECHNOLOGY_ICON_OPTIONS.map((icon) => [icon.slug, icon]))
export const TECHNOLOGY_ICON_ALIASES: Record<string, string> = {
  "actix": "actix",
  "actixweb": "actix",
  "airflow": "apacheairflow",
  "amqp": "rabbitmq",
  "angular": "angular",
  "angularjs": "angular",
  "ansible": "ansible",
  "antd": "antdesign",
  "antdesign": "antdesign",
  "apacheairflow": "apacheairflow",
  "apacheavro": "apacheavro",
  "apachecassandra": "apachecassandra",
  "apacheflink": "apacheflink",
  "apachejmeter": "apachejmeter",
  "apachekafka": "apachekafka",
  "apachemaven": "apachemaven",
  "apachepulsar": "apachepulsar",
  "apachesolr": "apachesolr",
  "apachespark": "apachespark",
  "astraluv": "uv",
  "astro": "astro",
  "astrobuild": "astro",
  "avro": "apacheavro",
  "bash": "shell",
  "bigquery": "googlebigquery",
  "bootstrap": "bootstrap",
  "bun": "bun",
  "bunsh": "bun",
  "c": "sharp",
  "cassandra": "apachecassandra",
  "celery": "celery",
  "chakra": "chakraui",
  "chakraui": "chakraui",
  "clang": "cplusplus",
  "clickhouse": "clickhouse",
  "clj": "clojure",
  "clojure": "clojure",
  "cmake": "cmake",
  "composer": "composer",
  "couchbase": "couchbase",
  "cplusplus": "cplusplus",
  "cpp": "cplusplus",
  "csharp": "sharp",
  "cxx": "cplusplus",
  "cypress": "cypress",
  "dart": "dart",
  "datadog": "datadog",
  "delphi": "delphi",
  "dependabot": "dependabot",
  "django": "django",
  "docker": "docker",
  "docusaurus": "docusaurus",
  "dotnet": "sharp",
  "ecmascript": "javascript",
  "elastic": "elasticsearch",
  "elasticsearch": "elasticsearch",
  "elixir": "elixir",
  "envoy": "envoyproxy",
  "envoyproxy": "envoyproxy",
  "erlang": "erlang",
  "esbuild": "esbuild",
  "express": "express",
  "expressjs": "express",
  "f": "fsharp",
  "fastapi": "fastapi",
  "fastify": "fastify",
  "flask": "flask",
  "flink": "apacheflink",
  "fluentbit": "fluentbit",
  "fluentd": "fluentd",
  "flux": "flux",
  "fluxcd": "flux",
  "fsharp": "fsharp",
  "gatling": "gatling",
  "gha": "githubactions",
  "gin": "gin",
  "gingonic": "gin",
  "git": "git",
  "githubactions": "githubactions",
  "gnumake": "make",
  "go": "go",
  "golang": "go",
  "googlebigquery": "googlebigquery",
  "gradle": "gradle",
  "grafana": "grafana",
  "grafanak6": "k6",
  "graphql": "graphql",
  "gunicorn": "gunicorn",
  "hashicorppacker": "packer",
  "hashicorpvault": "vault",
  "haskell": "haskell",
  "helm": "helm",
  "helmchart": "helm",
  "hibernate": "hibernate",
  "hibernateorm": "hibernate",
  "htmx": "htmx",
  "htmxorg": "htmx",
  "huggingface": "huggingface",
  "huggingfacetransformers": "huggingface",
  "jaeger": "jaeger",
  "javascript": "javascript",
  "jenkins": "jenkins",
  "jest": "jest",
  "jestjs": "jest",
  "jmeter": "apachejmeter",
  "jquery": "jquery",
  "js": "javascript",
  "julia": "julia",
  "junit": "junit5",
  "junit5": "junit5",
  "k6": "k6",
  "k8s": "kubernetes",
  "kafka": "apachekafka",
  "keras": "keras",
  "keycloak": "keycloak",
  "kibana": "kibana",
  "koa": "koa",
  "koajs": "koa",
  "kong": "kong",
  "konggateway": "kong",
  "kotlin": "kotlin",
  "kt": "kotlin",
  "kube": "kubernetes",
  "kubernetes": "kubernetes",
  "langchain": "langchain",
  "laravel": "laravel",
  "lit": "lit",
  "litelement": "lit",
  "lithtml": "lit",
  "logstash": "logstash",
  "lua": "lua",
  "make": "make",
  "makefile": "make",
  "mariadb": "mariadb",
  "markdown": "markdown",
  "materialui": "mui",
  "maven": "apachemaven",
  "md": "markdown",
  "mermaid": "mermaid",
  "mermaidjs": "mermaid",
  "minio": "minio",
  "mlflow": "mlflow",
  "mobx": "mobx",
  "mocha": "mocha",
  "mochajs": "mocha",
  "mongo": "mongodb",
  "mongodb": "mongodb",
  "mui": "mui",
  "mvn": "apachemaven",
  "mysql": "mysql",
  "nats": "natsdotio",
  "natsio": "natsdotio",
  "neo4j": "neo4j",
  "nestjs": "nestjs",
  "net": "sharp",
  "nextjs": "nextdotjs",
  "nginx": "nginx",
  "nodepackagemanager": "npm",
  "npm": "npm",
  "nuget": "nuget",
  "numpy": "numpy",
  "nuxt": "nuxt",
  "nuxtjs": "nuxt",
  "objectpascal": "delphi",
  "ocp": "redhatopenshift",
  "onnx": "onnx",
  "openapi": "swagger",
  "opensearch": "opensearch",
  "openshift": "redhatopenshift",
  "opentelemetry": "opentelemetry",
  "opentofu": "opentofu",
  "otel": "opentelemetry",
  "packer": "packer",
  "pandas": "pandas",
  "pascal": "delphi",
  "phoenix": "phoenixframework",
  "phoenixframework": "phoenixframework",
  "php": "php",
  "phpcomposer": "composer",
  "pinia": "pinia",
  "pnpm": "pnpm",
  "podman": "podman",
  "poetry": "poetry",
  "polars": "polars",
  "postgres": "postgresql",
  "postgresql": "postgresql",
  "prefect": "prefect",
  "prometheus": "prometheus",
  "pulsar": "apachepulsar",
  "pulumi": "pulumi",
  "py": "python",
  "pydantic": "pydantic",
  "pyspark": "apachespark",
  "pytest": "pytest",
  "python": "python",
  "pythonpoetry": "poetry",
  "pythonsphinx": "sphinx",
  "pytorch": "pytorch",
  "quarkus": "quarkus",
  "qwik": "qwik",
  "qwikjs": "qwik",
  "r": "r",
  "rabbit": "rabbitmq",
  "rabbitmq": "rabbitmq",
  "rails": "rubyonrails",
  "react": "react",
  "reactjs": "react",
  "reactquery": "reactquery",
  "redis": "redis",
  "redux": "redux",
  "reduxtoolkit": "redux",
  "remix": "remix",
  "remixrun": "remix",
  "renovate": "renovate",
  "renovatebot": "renovate",
  "rlang": "r",
  "rollup": "rollupdotjs",
  "rollupjs": "rollupdotjs",
  "rstats": "r",
  "rtk": "redux",
  "ruby": "ruby",
  "rubyonrails": "rubyonrails",
  "rust": "rust",
  "rustlang": "rust",
  "rxjs": "reactivex",
  "scala": "scala",
  "scikitlearn": "scikitlearn",
  "scipy": "scipy",
  "scylla": "scylladb",
  "scylladb": "scylladb",
  "selenium": "selenium",
  "seleniumwebdriver": "selenium",
  "sentry": "sentry",
  "sh": "shell",
  "shadcn": "shadcnui",
  "shadcnui": "shadcnui",
  "shell": "shell",
  "sklearn": "scikitlearn",
  "snowflake": "snowflake",
  "snyk": "snyk",
  "solid": "solid",
  "solidjs": "solid",
  "solr": "apachesolr",
  "sonar": "sonar",
  "sonarqube": "sonar",
  "spark": "apachespark",
  "sphinx": "sphinx",
  "spring": "spring_creators",
  "springboot": "springboot",
  "springframework": "spring_creators",
  "sqlalchemy": "sqlalchemy",
  "sqlite": "sqlite",
  "sqlite3": "sqlite",
  "storybook": "storybook",
  "svelte": "svelte",
  "sveltejs": "svelte",
  "swagger": "swagger",
  "swift": "swift",
  "symfony": "symfony",
  "tailwind": "tailwindcss",
  "tailwindcss": "tailwindcss",
  "tanstackquery": "reactquery",
  "tanstackreactquery": "reactquery",
  "teamcity": "teamcity",
  "tensorflow": "tensorflow",
  "terraform": "terraform",
  "tf": "tensorflow",
  "tofu": "opentofu",
  "torch": "pytorch",
  "transformers": "huggingface",
  "trivy": "trivy",
  "ts": "typescript",
  "typescript": "typescript",
  "uv": "uv",
  "uvpackagemanager": "uv",
  "vagrant": "vagrant",
  "vault": "vault",
  "vite": "vite",
  "vitejs": "vite",
  "vitest": "vitest",
  "vue": "vuedotjs",
  "vuejs": "vuedotjs",
  "webpack": "webpack",
  "yarn": "yarn",
  "yarnpkg": "yarn"
}
